---
# This will install nagios

- name: install nagios
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
   - nagios
   - nagios-plugins
   - nagios-plugins-nrpe
   - nagios-plugins-ping
   - nagios-plugins-ssh
   - nagios-plugins-http
   - nagios-plugins-mysql
   - nagios-devel
  notify: restart httpd

- name: create nagios config dir
  file:
    path: /etc/nagios/ansible-managed
    state: directory

- name: create nagios query handler socket dir
  file:
    path: /var/log/nagios/rw
    state: directory
    owner: nagios
    group: nagios

- name: configure nagios
  copy:
    src: nagios.cfg
    dest: /etc/nagios/nagios.cfg
  notify: restart nagios

- name: configure localhost monitoring
  copy:
    src: localhost.cfg
    dest: /etc/nagios/objects/localhost.cfg
  notify: restart nagios

- name: configure nagios services
  copy:
    src: ansible-managed-services.cfg
    dest: /etc/nagios/

- name: create the nagios object files
  template:
    src: "{{ item + '.j2' }}"
    dest: /etc/nagios/ansible-managed/"{{ item }}"
  with_items:
   - webservers.cfg
   - dbservers.cfg
   - lbservers.cfg
  notify: restart nagios

- name: FIXME set selinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Configure firewall for access
  firewalld:
    permanent: yes
    service: http
    state: enabled
    immediate: yes
  tags: fw

- name: start nagios
  service:
    name: nagios
    state: started
    enabled: yes
