---
- name: provision azure host
  hosts: localhost
  connection: local
  vars_files:
    - azure_vars.yml
  vars:
    azure_virtual_network: "{{ vm_name }}"
    azure_subnet: "{{ vm_name }}"
    azure_virtual_machine: "{{ vm_name }}"
    azure_resource_group: "{{ vm_name }}"

  tasks:
  - name: create Azure resource group
    azure_rm_resourcegroup:
      name: '{{azure_resource_group}}'
      location: westeurope
      state: present
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      tenant: "{{ tenant }}"
      client_id: "{{ client_id }}"

  - name: create Azure virtual network in resource group
    azure_rm_virtualnetwork:
      name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefixes_cidr:
      - 10.1.0.0/16
      state: present
  
  - name: create Azure subnet in virtualnetwork
    azure_rm_subnet:
      name: '{{azure_subnet}}'
      state: present
      virtual_network_name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefix_cidr: 10.1.0.0/24

  - name: provision new Azure virtual host
    azure_rm_virtualmachine:
      admin_username: '{{admin_username}}'
      admin_password: '{{admin_password}}'
      os_type: Linux
      image:
        offer: "RHEL"
        publisher: "RedHat"
        sku: "7.3"
        version: "7.3.2017032021"
      name: '{{ azure_virtual_machine }}'
      resource_group: '{{azure_resource_group}}'
      state: present
      vm_size: Standard_DS1_v2
      open_ports: 80,443
      virtual_network_name: '{{azure_virtual_network}}'
      subnet_name: '{{azure_subnet}}'

  - name: Get Public IP
    azure_rm_publicipaddress_facts:
      resource_group: '{{ azure_resource_group }}'
      name: '{{ azure_virtual_machine }}01'
    register: azure_ip

  - debug:
      msg: "Public IP: {{ azure_ip.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
