# Configure and deploy the load balancer(s).
- hosts: role_webserver
  become: yes
  name: Gather facts from webservers
  tasks: [ ]

- hosts: role_lbserver
  become: yes

  roles:
  - haproxy

  tags:
  - lb
