---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  become: yes
  roles:
  - common

# Configure and deploy database servers.
- hosts: role_dbserver

  roles:
  - db

  tags:
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: role_webserver

  roles:
  - base-apache
  - web

  tags:
  - web

# Configure and deploy the load balancer(s).
- hosts: role_lbserver

  roles:
  - haproxy

  tags:
  - lb

# Configure and deploy the Nagios monitoring node(s).
- hosts: role_monserver

  roles:
  - base-apache
  - nagios

  tags:
  - monintoring
