---
- name: install webserver
  hosts: all

  tasks:

  - name: Install http and php etc
    yum:
      name: "{{ item }}"
      state: present
    with_items:
     - httpd

  - name: http service state
    service:
      name: httpd
      state: started
      enabled: yes
