---
- name: install webserver
  hosts: Role_web_server

  tasks:

  - name: Install http and php etc
    yum:
      name:
        - httpd
        - php
      state: present

  - name: http service state
    service:
      name: httpd
      state: started
      enabled: yes

  - name: open up the firewall ports
    firewalld:
      service: https
      permanent: yes
      state: enabled
