---
- name: install webserver
  hosts: web_server

  tasks:

  - name: Install http and php etc
    yum:
      name: "{{ item }}"
      state: present
    with_items:
     - http
     - php

  - name: http service state
    service:
      name: httpd
      state: started
      enabled: yes
