---
# refresh git repo to webservers
- name: Update website
  hosts: "{{ 'webservers' }}"

  tasks:
  - name: Copy the code from repository
    git: repo={{ repository }} version={{ webapp_version }} dest=/var/www/html/
