---
# refresh git repo to webservers
- name: Update website
  hosts: Role_web_servers

  tasks:
  - name: Copy the code from repository
    git: repo={{ repository }}website_{{ CUSTOMER }}.git  version={{ webapp_version }} dest=/var/www/html/
