---
# refresh website from git to webservers
- name: Update website
  hosts: role_webserver
  become: yes

  tasks:
  - name: Copy the code from repository
    git:
      repo: "{{ repository }}/website_{{ customer }}.git"
      dest: /var/www/html/
